"""add edge path waypoints

Revision ID: 8b1a0d8ea70f
Revises: f90aa440ef2e
Create Date: 2026-09-30 13:02:17.835305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8b1a0d8ea70f'
down_revision: Union[str, Sequence[str], None] = 'f90aa440ef2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('path', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'path')
    # ### end Alembic commands ###
