"""add path segments

Revision ID: e6ef3b96c436
Revises: 8b1a0d8ea70f
Create Date: 2026-09-30 15:41:05.685761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e6ef3b96c436'
down_revision: Union[str, Sequence[str], None] = '8b1a0d8ea70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('path_segments')
    # ### end Alembic commands ###
