"""phase 1 data layer: all entities

Revision ID: f90aa440ef2e
Revises:
Create Date: 2026-07-05 21:01:53.165250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "f90aa440ef2e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column(
            "footprint",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # NOTE: no explicit gist index here — geoalchemy2 already creates
    # idx_buildings_footprint during create_table (spatial_index=True).
    op.create_table(
        "sync_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("payload_url", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "staff", "student", name="user_role"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "checkpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("qr_code_id", sa.Integer(), nullable=True),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["building_id"], ["buildings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["qr_code_id"],
            ["qrcodes.id"],
            name="fk_checkpoints_qr_code_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checkpoints_building_id"), "checkpoints", ["building_id"], unique=False
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["building_id"], ["buildings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_departments_building_id"), "departments", ["building_id"], unique=False
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "type",
            sa.Enum("classroom", "lab", "seminar_hall", "office", name="room_type"),
            nullable=False,
        ),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["building_id"], ["buildings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rooms_building_id"), "rooms", ["building_id"], unique=False
    )
    op.create_table(
        "edges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("checkpoint_a_id", sa.Integer(), nullable=False),
        sa.Column("checkpoint_b_id", sa.Integer(), nullable=False),
        sa.Column("distance_meters", sa.Float(), nullable=False),
        sa.Column("walking_time_estimate_sec", sa.Integer(), nullable=False),
        sa.Column("is_indoor", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkpoint_a_id"], ["checkpoints.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["checkpoint_b_id"], ["checkpoints.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checkpoint_a_id", "checkpoint_b_id", name="uq_edge_pair"),
    )
    op.create_index(
        op.f("ix_edges_checkpoint_a_id"), "edges", ["checkpoint_a_id"], unique=False
    )
    op.create_index(
        op.f("ix_edges_checkpoint_b_id"), "edges", ["checkpoint_b_id"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("poster_url", sa.String(length=500), nullable=True),
        sa.CheckConstraint(
            "(building_id IS NULL) != (room_id IS NULL)",
            name="ck_event_exactly_one_location",
        ),
        sa.ForeignKeyConstraint(["building_id"], ["buildings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_id"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "qrcodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("checkpoint_id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.String(length=255), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"], ["checkpoints.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checkpoint_id"),
        sa.UniqueConstraint("payload"),
    )
    # use_alter FK is skipped inside CREATE TABLE; add it now that qrcodes exists.
    op.create_foreign_key(
        "fk_checkpoints_qr_code_id",
        "checkpoints",
        "qrcodes",
        ["qr_code_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_checkpoints_qr_code_id", "checkpoints", type_="foreignkey")
    op.drop_table("qrcodes")
    op.drop_table("events")
    op.drop_index(op.f("ix_edges_checkpoint_b_id"), table_name="edges")
    op.drop_index(op.f("ix_edges_checkpoint_a_id"), table_name="edges")
    op.drop_table("edges")
    op.drop_index(op.f("ix_rooms_building_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_departments_building_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_checkpoints_building_id"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("sync_snapshots")
    op.drop_table("buildings")
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="room_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
